<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE qalab [<!ELEMENT qalab (summary,file*)>
<!ATTLIST qalab version CDATA #REQUIRED>
<!ELEMENT summary (summaryresult*)>
<!ELEMENT file (result+)>
<!ATTLIST file id ID #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT result EMPTY>
<!ATTLIST result date CDATA #REQUIRED>
<!ATTLIST result statvalue CDATA #REQUIRED>
<!ATTLIST result type CDATA #REQUIRED>
<!ELEMENT summaryresult EMPTY>
<!ATTLIST summaryresult date CDATA #REQUIRED>
<!ATTLIST summaryresult statvalue CDATA #REQUIRED>
<!ATTLIST summaryresult filecount CDATA #REQUIRED>
<!ATTLIST summaryresult type CDATA #REQUIRED>
]>
<qalab version="1.1">
    <summary>
        <summaryresult date="2007-06-06" filecount="9" statvalue="24" type="checkstyle"/>
        <summaryresult date="2007-06-06" filecount="1" statvalue="1" type="pmd"/>
        <summaryresult date="2007-06-06" filecount="3" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2007-06-07" filecount="9" statvalue="24" type="checkstyle"/>
        <summaryresult date="2007-06-07" filecount="1" statvalue="1" type="pmd"/>
        <summaryresult date="2007-06-07" filecount="3" statvalue="100" type="cobertura-branch"/>
        <summaryresult date="2007-06-16" filecount="12" statvalue="60" type="checkstyle"/>
        <summaryresult date="2007-06-16" filecount="1" statvalue="1" type="pmd"/>
        <summaryresult date="2007-06-16" filecount="4" statvalue="100" type="cobertura-branch"/>
    </summary>
    <file id="org_trails_test_functional_FunctionalTest.java" path="org/trails/test/functional/FunctionalTest.java">
        <result date="2007-06-06" statvalue="13" type="checkstyle"/>
        <result date="2007-06-06" statvalue="100" type="cobertura-branch"/>
        <result date="2007-06-07" statvalue="13" type="checkstyle"/>
        <result date="2007-06-07" statvalue="100" type="cobertura-branch"/>
        <result date="2007-06-16" statvalue="14" type="checkstyle"/>
        <result date="2007-06-16" statvalue="100" type="cobertura-branch"/>
    </file>
    <file id="org_trails_component_ComponentTest.java" path="org/trails/component/ComponentTest.java">
        <result date="2007-06-06" statvalue="8" type="checkstyle"/>
        <result date="2007-06-06" statvalue="1" type="pmd"/>
        <result date="2007-06-06" statvalue="100" type="cobertura-branch"/>
        <result date="2007-06-07" statvalue="8" type="checkstyle"/>
        <result date="2007-06-07" statvalue="1" type="pmd"/>
        <result date="2007-06-07" statvalue="100" type="cobertura-branch"/>
        <result date="2007-06-16" statvalue="8" type="checkstyle"/>
        <result date="2007-06-16" statvalue="1" type="pmd"/>
        <result date="2007-06-16" statvalue="100" type="cobertura-branch"/>
    </file>
    <file id="org_trails_i18n_package.html" path="org/trails/i18n/package.html">
        <result date="2007-06-06" statvalue="1" type="checkstyle"/>
        <result date="2007-06-07" statvalue="1" type="checkstyle"/>
        <result date="2007-06-16" statvalue="1" type="checkstyle"/>
    </file>
    <file id="org_trails_test_functional_package.html" path="org/trails/test/functional/package.html">
        <result date="2007-06-06" statvalue="1" type="checkstyle"/>
        <result date="2007-06-07" statvalue="1" type="checkstyle"/>
        <result date="2007-06-16" statvalue="1" type="checkstyle"/>
    </file>
    <file id="org_trails_component_package.html" path="org/trails/component/package.html">
        <result date="2007-06-06" statvalue="1" type="checkstyle"/>
        <result date="2007-06-07" statvalue="1" type="checkstyle"/>
        <result date="2007-06-16" statvalue="1" type="checkstyle"/>
    </file>
    <file id="org_trails_i18n_TestLocaleHolder.java" path="org/trails/i18n/TestLocaleHolder.java">
        <result date="2007-06-06" statvalue="100" type="cobertura-branch"/>
        <result date="2007-06-07" statvalue="100" type="cobertura-branch"/>
        <result date="2007-06-16" statvalue="100" type="cobertura-branch"/>
    </file>
    <file id="org_trails_test_MockableTransactionalTestCase.java" path="org/trails/test/MockableTransactionalTestCase.java">
        <result date="2007-06-16" statvalue="34" type="checkstyle"/>
        <result date="2007-06-16" statvalue="100" type="cobertura-branch"/>
    </file>
    <file id="org_trails_test_package.html" path="org/trails/test/package.html">
        <result date="2007-06-16" statvalue="1" type="checkstyle"/>
    </file>
</qalab>
